######################################################################
## 4. MODEL SELECTION AND ANALYSIS FOR PLSGLM ON FULL DATA
######################################################################
rm(list=ls())
gc()
source("tools.r")
library(ggplot2)

memory.limit(64000)

#######################
## Data processing
#######################

# Plate 1.1
plate1.1 <- read.csv("yield_data\\plate1.1.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate1.1_pdt <- plate1.1$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate1.1_pdt))
dim(plate.data) <- c(24,16)
plate.data1.1 <- t(plate.data)

# Plate 1.2
plate1.2 <- read.csv("yield_data\\plate1.2.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate1.2_pdt <- plate1.2$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate1.2_pdt))
dim(plate.data) <- c(24,16)
plate.data1.2 <- t(plate.data)

# Plate 1.3
plate1.3 <- read.csv("yield_data\\plate1.3.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate1.3_pdt <- plate1.3$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate1.3_pdt))
dim(plate.data) <- c(24,16)
plate.data1.3 <- t(plate.data)

# Plate 1.4
plate1.4 <- read.csv("yield_data\\plate1.4.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate1.4_pdt <- plate1.4$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate1.4_pdt))
dim(plate.data) <- c(24,16)
plate.data1.4 <- t(plate.data)

# stitch Plate 1 together into one 32x48 matrix
plate1.top <- cbind(plate.data1.1, plate.data1.2)
plate1.bottom <- cbind(plate.data1.3, plate.data1.4)
plate1 <- rbind(plate1.top, plate1.bottom)

# Plate 2.1
plate2.1 <- read.csv("yield_data\\plate2.1.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate2.1_pdt <- plate2.1$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate2.1_pdt))
dim(plate.data) <- c(24,16)
plate.data2.1 <- t(plate.data)

# Plate 2.2
plate2.2 <- read.csv("yield_data\\plate2.2.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate2.2_pdt <- plate2.2$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate2.2_pdt))
dim(plate.data) <- c(24,16)
plate.data2.2 <- t(plate.data)

# Plate 2.3
plate2.3 <- read.csv("yield_data\\plate2.3.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate2.3_pdt <- plate2.3$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate2.3_pdt))
dim(plate.data) <- c(24,16)
plate.data2.3 <- t(plate.data)

# Plate 2.4
plate2.4 <- read.csv("yield_data\\plate2.4.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate2.4_pdt <- plate2.4$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate2.4_pdt))
dim(plate.data) <- c(24,16)
plate.data2.4 <- t(plate.data)

# stitch Plate 2 together into one 32x48 matrix
plate2.top <- cbind(plate.data2.1, plate.data2.2)
plate2.bottom <- cbind(plate.data2.3, plate.data2.4)
plate2 <- rbind(plate2.top, plate2.bottom)

# Plate 3.1
plate3.1 <- read.csv("yield_data\\plate3.1.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate3.1_pdt <- plate3.1$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate3.1_pdt))
dim(plate.data) <- c(24,16)
plate.data3.1 <- t(plate.data)

# Plate 3.2
plate3.2 <- read.csv("yield_data\\plate3.2.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate3.2_pdt <- plate3.2$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate3.2_pdt))
dim(plate.data) <- c(24,16)
plate.data3.2 <- t(plate.data)

# Plate 3.3
plate3.3 <- read.csv("yield_data\\plate3.3.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate3.3_pdt <- plate3.3$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate3.3_pdt))
dim(plate.data) <- c(24,16)
plate.data3.3 <- t(plate.data)

# Plate 3.4
plate3.4 <- read.csv("yield_data\\plate3.4.csv", header=TRUE, stringsAsFactors=FALSE, na.strings = "#DIV/0!")
plate3.4_pdt <- plate3.4$product_scaled[1:384]
plate.data <- as.matrix(as.numeric(plate3.4_pdt))
dim(plate.data) <- c(24,16)
plate.data3.4 <- t(plate.data)

# stitch Plate 3 together into one 32x48 matrix
plate3.top <- cbind(plate.data3.1, plate.data3.2)
plate3.bottom <- cbind(plate.data3.3, plate.data3.4)
plate3 <- rbind(plate3.top, plate3.bottom)

# Remove empty rows/cols
plate1_nocontrols <- plate1[c(-1,-5,-9,-13,-20,-24,-28,-32), c(-16,-32,-48)] 
plate2_nocontrols <- plate2[, c(-16,-32,-48)]
plate3_nocontrols <- plate3[, c(-16,-32,-48)]
plate1_nocontrols_v <- as.vector(t(plate1_nocontrols))
plate2_nocontrols_v <- as.vector(t(plate2_nocontrols))
plate3_nocontrols_v <- as.vector(t(plate3_nocontrols))
yield_data <- c(plate1_nocontrols_v, plate2_nocontrols_v, plate3_nocontrols_v)

# Load output table generated by python script
output.table <- read.csv("yield_data\\output_table.csv", header=TRUE)

# Scaled variables
y <- as.data.frame(yield_data[-which(is.na(yield_data))]/100)
x <- as.data.frame(output.table[-which(is.na(yield_data)),])
#x <- as.data.frame(scale(output.table[-which(is.na(yield_data)),]))
tt <- (1:length(y[,1]))/length(y)

# Add three artificial descriptors for additives
xc <- x
set.seed(2134)
c1 <- factor(xc[,1])
c2 <- factor(xc[,3])
c3 <- factor(xc[,4])
levels(c1) <- runif(22)
levels(c2) <- rnorm(22)
levels(c3) <- runif(22)
xc <- cbind(cbind(as.numeric(c1),as.numeric(c2),as.numeric(c3)),xc)
colnames(xc)[1:3] <- c("add_new1","add_new2","add_new3")

xs <- xc[,c(4,23,50,60)]
colnames(xs) <- c("additive","aryl_halide","base","ligand")

a <- rep(NA,ncol(xs))
for (i in 1:ncol(xs)) a[i] <- length(unique(xs[,i]))
xcf <- matrix(NA,nrow(xs),sum(a))
b <- cumsum(a)
colnames(xcf) <- rep(colnames(xs),times=a)
colnum <- order(unique(xs[,1]))
for (i in 2:ncol(xs)) colnum <- c(colnum,order(unique(xs[,i])))
colnames(xcf) <- paste(colnames(xcf),colnum)
for (i in 1:nrow(xs))
{
  for (j in 1:length(a))
  {
    res <- rep(0, a[j])
    where <- match( xs[i,j], unique(xs[,j]) )
    res[ where ] <- 1 
    xcf[i,(max(b[j-1],0)+1):b[j]] <- res
  }
}
for (i in 1:length(b))
{
  ind <- match(xcf[,b[i]],1)==1
  xcf[ind,(max(b[i-1],0)+1):b[i]] <- -1
}
xcf <- xcf[,-b]
x.all <- xcf

# Identify label ijkl for yield
for (ijkl in 1:length(tt)) {
  add.i <- colnames(x.all)[which(x.all[ijkl,]!=0)][1]
  add.I <- sum(grepl("additive",colnames(x.all)[which(x.all[ijkl,]!=0)]))
  if (add.I>1) add.i <- "additive 0"
  ary.j <- colnames(x.all)[which(x.all[ijkl,]!=0)][1+add.I]
  ary.J <- sum(grepl("aryl_halide",colnames(x.all)[which(x.all[ijkl,]!=0)]))
  if (ary.J>1) ary.j <- "aryl_halide 0"
  bas.k <- colnames(x.all)[which(x.all[ijkl,]!=0)][1+add.I+ary.J]
  bas.K <- sum(grepl("base",colnames(x.all)[which(x.all[ijkl,]!=0)]))
  if (bas.K>1) bas.k <- "base 0"
  lig.l <- colnames(x.all)[which(x.all[ijkl,]!=0)][1+add.I+ary.J+bas.K]
  lig.L <- sum(grepl("ligand",colnames(x.all)[which(x.all[ijkl,]!=0)]))
  if (lig.L>1) lig.l <- "ligand 0"
  rownames(y)[ijkl] <- paste(add.i, ary.j, bas.k, lig.l, sep=":")
}
y.all <- y

# Mixed terms with 2-levels combinations
xx <- rep(1,nrow(xcf))
bb <- cumsum(a-1)
for (j in 1:3) {
  for (i in (max(bb[j-1],0)+1):bb[j]) {
    xxp <- xcf[,i]*xcf[,-c(1:bb[j])]
    colnames(xxp) <- paste(colnames(xcf)[i],colnames(xcf[,-c(1:bb[j])]),sep=":")
    xx <- cbind(xx,xxp)
  }
}
xx <- cbind(xcf,xx[,-1])
xx.all <- xx

# Mixed terms with 3-levels combinations
xcf1 <- xcf
colnames(xcf1) <- c(rep("additive",21),rep("aryl_halide",14),rep("base",2),rep("ligand",3))
xx1 <- xx[,-c(1:40)]

xxx <- rep(1,nrow(xcf))
ind <- rep(TRUE,ncol(xx1))
for (j in 1:2) {
  ind <- as.logical((!grepl(colnames(xcf1)[bb[j]],colnames(xx1)))*(ind))
  for (i in (max(bb[j-1],0)+1):bb[j]) {
    xxxp <- xcf[,i]*xx1[,ind]
    colnames(xxxp) <- paste(colnames(xcf)[i],colnames(xx1)[ind],sep=":")
    xxx <- cbind(xxx,xxxp)
  }
}
xxx <- cbind(xx,xxx[,-1])
xxx.all <- xxx

# Mixed terms with 4-levels combinations
xxx1 <- xxx[,-c(1:515)]

xxxx <- rep(NA,nrow(xcf))
for (i in 1:21) {
  xxxxp <- xcf[,i]*xxx1[,1597:1680]
  colnames(xxxxp) <- paste(colnames(xcf)[i],colnames(xxx1)[1597:1680],sep=":")
  xxxx <- cbind(xxxx,xxxxp)
}
xxxx <- cbind(xxx,xxxx[,-1])
xxxx.all <- xxxx

##################################
## PLSGLM with CV on 2/3/4 levels
##################################

nc <- (1:14)*3
cor2NS.all <- rmse2NS.all <- ll2NS.all <- dof2NS.all <- kap2NS.all <- rep(NA,max(nc))
cor3NS.all <- rmse3NS.all <- ll3NS.all <- dof3NS.all <- kap3NS.all <- rep(NA,max(nc))
cor4NS.all <- rmse4NS.all <- ll4NS.all <- dof4NS.all <- kap4NS.all <- rep(NA,max(nc))

for (i in nc) {
  
  print(paste("Checking",i,"comps..."))
  
  # 2-levels
  pls2NS.all <- plsglm.cb(xx.all, y.all, i, scaling=FALSE, maxit=10, tol=0.0545)
  gc()
  
  beta.hat.pls2NS.all <- pls2NS.all$BETA[,,i]
  W.hat.pls2NS.all <- pls2NS.all$W[,,i]
  Z.hat.pls2NS.all <- pls2NS.all$Z[,,i]
  R.hat.pls2NS.all <- (pls2NS.all$R[[i]])[-1,]
  T.hat.pls2NS.all <- xx.all%*%R.hat.pls2NS.all
  eta.hat.pls2NS.all <- as.vector(as.matrix(xx.all)%*%beta.hat.pls2NS.all[-1]+beta.hat.pls2NS.all[1])
  mu.hat.pls2NS.all <- kappa1(eta.hat.pls2NS.all)
  
  cor2NS.all[i] <- cor(mu.hat.pls2NS.all,y.all[,1])
  rmse2NS.all[i] <- sqrt(mean((mu.hat.pls2NS.all*100-y.all[,1]*100)^2))
  ll2NS.all[i] <- sum(y.all[,1]*eta.hat.pls2NS.all-kappa0(eta.hat.pls2NS.all))
  kap2NS.all[i] <- kappa(T.hat.pls2NS.all)
  dof2NS.all[i] <- dof.pls(sqrt(W.hat.pls2NS.all)%*%xx.all, sqrt(W.hat.pls2NS.all)%*%Z.hat.pls2NS.all, i, eigen(t(xx.all)%*%W.hat.pls2NS.all%*%xx.all)$values)$DOF[i]
  
  # 3-levels
  pls3NS.all <- plsglm.cb(xxx.all, y.all, i, scaling=FALSE, maxit=10, tol=0.0545)
  gc()
  
  beta.hat.pls3NS.all <- pls3NS.all$BETA[,,i]
  W.hat.pls3NS.all <- pls3NS.all$W[,,i]
  Z.hat.pls3NS.all <- pls3NS.all$Z[,,i]
  R.hat.pls3NS.all <- (pls3NS.all$R[[i]])[-1,]
  T.hat.pls3NS.all <- xxx.all%*%R.hat.pls3NS.all
  eta.hat.pls3NS.all <- as.vector(as.matrix(xxx.all)%*%beta.hat.pls3NS.all[-1]+beta.hat.pls3NS.all[1])
  mu.hat.pls3NS.all <- kappa1(eta.hat.pls3NS.all)
  
  cor3NS.all[i] <- cor(mu.hat.pls3NS.all,y.all[,1])
  rmse3NS.all[i] <- sqrt(mean((mu.hat.pls3NS.all*100-y.all[,1]*100)^2))
  ll3NS.all[i] <- sum(y.all[,1]*eta.hat.pls3NS.all-kappa0(eta.hat.pls3NS.all))
  kap3NS.all[i] <- kappa(T.hat.pls3NS.all)
  dof3NS.all[i] <- dof.pls(sqrt(W.hat.pls3NS.all)%*%xxx.all, sqrt(W.hat.pls3NS.all)%*%Z.hat.pls3NS.all, i, eigen(t(xxx.all)%*%W.hat.pls3NS.all%*%xxx.all)$values)$DOF[i]
  
  # 4-levels
  pls4NS.all <- plsglm.cb(xxxx.all, y.all, i, scaling=FALSE, maxit=10, tol=0.0545)
  gc()
  
  beta.hat.pls4NS.all <- pls4NS.all$BETA[,,i]
  W.hat.pls4NS.all <- pls4NS.all$W[,,i]
  Z.hat.pls4NS.all <- pls4NS.all$Z[,,i]
  R.hat.pls4NS.all <- (pls4NS.all$R[[i]])[-1,]
  T.hat.pls4NS.all <- xxxx.all%*%R.hat.pls4NS.all
  eta.hat.pls4NS.all <- as.vector(as.matrix(xxxx.all)%*%beta.hat.pls4NS.all[-1]+beta.hat.pls4NS.all[1])
  mu.hat.pls4NS.all <- kappa1(eta.hat.pls4NS.all)
  
  cor4NS.all[i] <- cor(mu.hat.pls4NS.all,y.all[,1])
  rmse4NS.all[i] <- sqrt(mean((mu.hat.pls4NS.all*100-y.all[,1]*100)^2))
  ll4NS.all[i] <- sum(y.all[,1]*eta.hat.pls4NS.all-kappa0(eta.hat.pls4NS.all))
  kap4NS.all[i] <- kappa(T.hat.pls4NS.all)
  dof4NS.all[i] <- dof.pls(sqrt(W.hat.pls4NS.all)%*%xxxx.all, sqrt(W.hat.pls4NS.all)%*%Z.hat.pls4NS.all, i, eigen(t(xxxx.all)%*%W.hat.pls4NS.all%*%xxxx.all)$values)$DOF[i]
  
}
gc()

# Save results
write(cor2NS.all, file="anova_cor2NS.txt", sep="\n")
write(rmse2NS.all, file="anova_rmse2NS.txt", sep="\n")
write(ll2NS.all, file="anova_ll2NS.txt", sep="\n")
write(dof2NS.all, file="anova_dof2NS.txt", sep="\n")
write(kap2NS.all, file="anova_kap2NS.txt", sep="\n")

write(cor3NS.all, file="anova_cor3NS.txt", sep="\n")
write(rmse3NS.all, file="anova_rmse3NS.txt", sep="\n")
write(ll3NS.all, file="anova_ll3NS.txt", sep="\n")
write(dof3NS.all, file="anova_dof3NS.txt", sep="\n")
write(kap3NS.all, file="anova_kap3NS.txt", sep="\n")

write(cor4NS.all, file="anova_cor4NS.txt", sep="\n")
write(rmse4NS.all, file="anova_rmse4NS.txt", sep="\n")
write(ll4NS.all, file="anova_ll4NS.txt", sep="\n")
write(dof4NS.all, file="anova_dof4NS.txt", sep="\n")
write(kap4NS.all, file="anova_kap4NS.txt", sep="\n")

#Load results
cor2NS.all <- scan(file="anova_cor2NS.txt", sep="\n")
rmse2NS.all <- scan(file="anova_rmse2NS.txt", sep="\n")
ll2NS.all <- scan(file="anova_ll2NS.txt", sep="\n")
dof2NS.all <- scan(file="anova_dof2NS.txt", sep="\n")
kap2NS.all <- scan(file="anova_kap2NS.txt", sep="\n")

cor3NS.all <- scan(file="anova_cor3NS.txt", sep="\n")
rmse3NS.all <- scan(file="anova_rmse3NS.txt", sep="\n")
ll3NS.all <- scan(file="anova_ll3NS.txt", sep="\n")
dof3NS.all <- scan(file="anova_dof3NS.txt", sep="\n")
kap3NS.all <- scan(file="anova_kap3NS.txt", sep="\n")

cor4NS.all <- scan(file="anova_cor4NS.txt", sep="\n")
rmse4NS.all <- scan(file="anova_rmse4NS.txt", sep="\n")
ll4NS.all <- scan(file="anova_ll4NS.txt", sep="\n")
dof4NS.all <- scan(file="anova_dof4NS.txt", sep="\n")
kap4NS.all <- scan(file="anova_kap4NS.txt", sep="\n")

# Visual results
pdf(file=paste("anova_all", ".pdf", sep=""), height=10, width=12)

df.all.rsq <- data.frame(nc=c(nc,nc,nc), 
                         type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                         rsq=c(cor2NS.all[nc]^2,cor3NS.all[nc]^2,cor4NS.all[nc]^2))
ggplot(data = df.all.rsq, aes(x = nc, y = rsq, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = bquote(R^2 ~"on full data"), col="Levels") +
  xlab("Latent dimensions") + ylab(bquote(R^2)) +
  scale_x_continuous(breaks=nc)

df.all.rmse <- data.frame(nc=c(nc,nc,nc), 
                          type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                          rmse=c(rmse2NS.all[nc],rmse3NS.all[nc],rmse4NS.all[nc]))
ggplot(data = df.all.rmse, aes(x = nc, y = rmse, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "RMSE on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("RMSE") +
  scale_x_continuous(breaks=nc)

df.all.logl <- data.frame(nc=c(nc,nc,nc), 
                          type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                          logl=c(ll2NS.all[nc],ll3NS.all[nc],ll4NS.all[nc]))
ggplot(data = df.all.logl, aes(x = nc, y = logl, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "Loglike on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("LogL") +
  scale_x_continuous(breaks=nc)

df.all.dof <- data.frame(nc=c(nc,nc,nc), 
                         type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                         dof=c(dof2NS.all[nc],dof3NS.all[nc],dof4NS.all[nc]))
ggplot(data = df.all.dof, aes(x = nc, y = dof, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "DoF on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("DoF") +
  scale_x_continuous(breaks=nc)

df.all.kap <- data.frame(nc=c(nc,nc,nc), 
                         type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                         kap=c(kap2NS.all[nc],kap3NS.all[nc],kap4NS.all[nc]))
ggplot(data = df.all.kap, aes(x = nc, y = kap, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "kappa on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("kappa") +
  scale_x_continuous(breaks=nc)

aic2NS.all <- 2*(1:max(nc))-2*ll2NS.all
aic3NS.all <- 2*(1:max(nc))-2*ll3NS.all
aic4NS.all <- 2*(1:max(nc))-2*ll4NS.all
df.all.aic <- data.frame(nc=c(nc,nc,nc), 
                         type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                         aic=c(aic2NS.all[nc],aic3NS.all[nc],aic4NS.all[nc]))
ggplot(data = df.all.aic, aes(x = nc, y = aic, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "m-AIC on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("m-AIC") +
  scale_x_continuous(breaks=nc)

aic2NS.all <- 2*dof2NS.all-2*ll2NS.all
aic3NS.all <- 2*dof3NS.all-2*ll3NS.all
aic4NS.all <- 2*dof4NS.all-2*ll4NS.all
df.all.aic <- data.frame(nc=c(nc,nc,nc), 
                         type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                         aic=c(aic2NS.all[nc],aic3NS.all[nc],aic4NS.all[nc]))
ggplot(data = df.all.aic, aes(x = nc, y = aic, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "dof-AIC on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("dof-AIC") +
  scale_x_continuous(breaks=nc)

kapaic2NS.all <- 2*kap2NS.all-2*ll2NS.all
kapaic3NS.all <- 2*kap3NS.all-2*ll3NS.all
kapaic4NS.all <- 2*kap4NS.all-2*ll4NS.all
df.all.kaic <- data.frame(nc=c(nc,nc,nc), 
                          type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                          kaic=c(kapaic2NS.all[nc],kapaic3NS.all[nc],kapaic4NS.all[nc]))
ggplot(data = df.all.kaic, aes(x = nc, y = kaic, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "kap-AIC on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("kap-AIC") +
  scale_x_continuous(breaks=nc)

bic2NS.all <- log(nrow(xx.all))*(1:max(nc))-2*ll2NS.all
bic3NS.all <- log(nrow(xxx.all))*(1:max(nc))-2*ll3NS.all
bic4NS.all <- log(nrow(xxxx.all))*(1:max(nc))-2*ll4NS.all
df.all.bic <- data.frame(nc=c(nc,nc,nc), 
                         type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                         bic=c(bic2NS.all[nc],bic3NS.all[nc],bic4NS.all[nc]))
ggplot(data = df.all.bic, aes(x = nc, y = bic, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "m-BIC on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("m-BIC") +
  scale_x_continuous(breaks=nc)

bic2NS.all <- log(nrow(xx.all))*dof2NS.all-2*ll2NS.all
bic3NS.all <- log(nrow(xxx.all))*dof3NS.all-2*ll3NS.all
bic4NS.all <- log(nrow(xxxx.all))*dof4NS.all-2*ll4NS.all
df.all.bic <- data.frame(nc=c(nc,nc,nc), 
                         type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                         bic=c(bic2NS.all[nc],bic3NS.all[nc],bic4NS.all[nc]))
ggplot(data = df.all.bic, aes(x = nc, y = bic, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "dof-BIC on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("dof-BIC") +
  scale_x_continuous(breaks=nc)

kapbic2NS.all <- log(nrow(xx.all))*kap2NS.all-2*ll2NS.all
kapbic3NS.all <- log(nrow(xxx.all))*kap3NS.all-2*ll3NS.all
kapbic4NS.all <- log(nrow(xxxx.all))*kap4NS.all-2*ll4NS.all
df.all.kbic <- data.frame(nc=c(nc,nc,nc), 
                          type=c(rep("2-lev",times=length(nc)),rep("3-lev",times=length(nc)),rep("4-lev",times=length(nc))),
                          kbic=c(kapbic2NS.all[nc],kapbic3NS.all[nc],kapbic4NS.all[nc]))
ggplot(data = df.all.kbic, aes(x = nc, y = kbic, col=type)) + 
  geom_point(size=4) + geom_line(size=2) + 
  theme(text = element_text(size = 40)) +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5))) +
  labs(title = "kap-BIC on full data", col="Levels") +
  xlab("Latent dimensions") + ylab("kap-BIC") +
  scale_x_continuous(breaks=nc)

dev.off()

# Select best models
nc3NS.all <- max(nc[which(kap3NS.all[nc]<50)]) # this gives 27 comps with kappa=32
p.all <- ncol(xxx.all)

# Best 3-levels model NS
# pls3NS.all <- plsglm.cb(xxx.all, y.all, nc3NS.all, scaling=FALSE, maxit=10, tol=0.0545)
# gc()
# saveRDS(pls3NS.all, file=paste("anova_best_pls3NS",nc3NS.all,".rds",sep=""))
pls3NS.all <- readRDS(file=paste("anova_best_pls3NS",nc3NS.all,".rds",sep=""))

beta.hat.pls3NS.all <- pls3NS.all$BETA[,,nc3NS.all]
coef.pls3 <- rbind(c("intercept",beta.hat.pls3NS.all[1]),data.frame(colnames(xxx.all),beta.hat.pls3NS.all[-1]))
write.table(coef.pls3, file=paste("anova_best_pls3NS",nc3NS.all,"_coeffs.txt",sep=""), sep=" ", row.names=FALSE, col.names=FALSE)
coef.pls3 <- read.table(file=paste("anova_best_pls3NS",nc3NS.all,"_coeffs.txt",sep=""))
coef.pls3[order(abs(as.numeric(coef.pls3[,2])),decreasing=TRUE),][1:30,]

W.hat.pls3NS.all <- pls3NS.all$W[,,nc3NS.all]        # weight matrix
R.hat.pls3NS.all <- (pls3NS.all$R[[nc3NS.all]])[-1,] # latent projection is not orthogonal
T.hat.pls3NS.all <- xxx.all%*%R.hat.pls3NS.all       # latent design
alpha.hat.pls3NS.all <- c(beta.hat.pls3NS.all[1], 
                          solve(t(R.hat.pls3NS.all)%*%R.hat.pls3NS.all)%*%t(R.hat.pls3NS.all)%*%beta.hat.pls3NS.all[-1]) # to fix non-orthogonality of R.hat.pls3NS.all

eta.hat.pls3NS.all <- as.vector(as.matrix(xxx.all)%*%beta.hat.pls3NS.all[-1]+beta.hat.pls3NS.all[1]) # estimated linear predictors
mu.hat.pls3NS.all <- kappa1(eta.hat.pls3NS.all)                                                      # estimated means

plot(y.all[,1], mu.hat.pls3NS.all) # sanity check for latent model
plot(y.all[,1], kappa1(as.vector(T.hat.pls3NS.all%*%alpha.hat.pls3NS.all[-1]+alpha.hat.pls3NS.all[1])))

kappa(T.hat.pls3NS.all)             # with 27 comps kappa=27.1514
cor(mu.hat.pls3NS.all,y.all[,1])^2  # with 27 comps R^2=0.9670

##################################
## Analysis of deviance residuals 
##################################

plot(eta.hat.pls3NS.all, g.link(mu.hat.pls3NS.all)) # our g.link is good approximation of inverse of kappa1

rd.hat.pls3NS.all <- (2*(y.all[,1]*g.link(y.all[,1])-kappa0(g.link(y.all[,1]))) - 2*(y.all[,1]*g.link(mu.hat.pls3NS.all)-kappa0(g.link(mu.hat.pls3NS.all))))  # positive deviance residuals
rd.hat.pls3NS.all <- sign(y.all[,1]-mu.hat.pls3NS.all)*rd.hat.pls3NS.all                                                                                      # signed deviance residuals

pdf("anova_all_res_dev.pdf",width=10,height=10)
df.rd.pls3NS <- data.frame(tt.all=(1:length(tt)), rd=rd.hat.pls3NS.all)
ggplot(data = df.rd.pls3NS, aes(x = tt.all, y = rd)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Deviance residuals",sep="")) +
  geom_point(color="cornflowerblue",size=3) + xlab("Observations") + ylab("Dev Res") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.rd.pls3NS, aes(x = rd)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Deviance residuals",sep="")) +
  geom_histogram(color="black", fill="cornflowerblue") + xlab("Dev Res") + ylab("Count") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

df.rd.pls3NS <- data.frame(mu=mu.hat.pls3NS.all, rd=rd.hat.pls3NS.all)
ggplot(data = df.rd.pls3NS, aes(x = mu, y = rd)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Fitted vs Dev Residuals",sep="")) +
  geom_point(color="cornflowerblue",size=3) + xlab("Fitted") + ylab("Dev Res") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))
dev.off()


##################################
## Analysis of Pearson residuals 
##################################

plot(eta.hat.pls3NS.all, kappa2(eta.hat.pls3NS.all))

rp.hat.pls3NS.all <- (y.all[,1]-mu.hat.pls3NS.all)/sqrt(diag(W.hat.pls3NS.all)) # standardized Pearson's residuals

pdf("anova_all_res_prs.pdf",width=10,height=10)
df.rp.pls3NS <- data.frame(tt.all=(1:length(tt)), mu=mu.hat.pls3NS.all, rp=rp.hat.pls3NS.all)
ggplot(data = df.rp.pls3NS, aes(x = tt.all, y = rp)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Pearson's residuals",sep="")) +
  geom_point(color="cornflowerblue",size=3) + xlab("Observations") + ylab("Prs Res") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.rp.pls3NS, aes(x = rp)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Pearson's residuals",sep="")) +
  geom_histogram(color="black", fill="cornflowerblue") + xlab("Prs Res") + ylab("Count") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.rp.pls3NS, aes(sample = scale(rp))) + theme(text = element_text(size = 40)) +
  labs(title = paste("Pearson's residuals",sep="")) +
  stat_qq() + xlab("Prs Res") + ylab("Normal") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.rp.pls3NS, aes(x = mu, y = rp)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Fitted vs Prs Residuals",sep="")) +
  geom_point(color="cornflowerblue",size=3) + xlab("Fitted") + ylab("Prs Res") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

out.hat.pls3NS.all <- which(abs(rp.hat.pls3NS.all)<1.5)
df.rp.pls3NS <- data.frame(tt.all=out.hat.pls3NS.all, mu=mu.hat.pls3NS.all[out.hat.pls3NS.all], rp=rp.hat.pls3NS.all[out.hat.pls3NS.all])
ggplot(data = df.rp.pls3NS, aes(x = tt.all, y = rp)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Pearson's residuals",sep="")) +
  geom_point(color="cornflowerblue",size=3) + xlab("Observations") + ylab("Prs Res") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.rp.pls3NS, aes(x = rp)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Pearson's residuals",sep="")) +
  geom_histogram(color="black", fill="cornflowerblue") + xlab("Prs Res") + ylab("Count") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.rp.pls3NS, aes(sample = scale(rp))) + theme(text = element_text(size = 40)) +
  labs(title = paste("Pearson's residuals",sep="")) +
  stat_qq() + xlab("Prs Res") + ylab("Normal") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.rp.pls3NS, aes(x = mu, y = rp)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Fitted vs Prs Residuals",sep="")) +
  geom_point(color="cornflowerblue",size=3) + xlab("Fitted") + ylab("Prs Res") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))
dev.off()


##################################
## Analysis of Anscombe residuals 
##################################

plot(mu.hat.pls3NS.all, g.link(mu.hat.pls3NS.all))
plot(mu.hat.pls3NS.all, V.link(mu.hat.pls3NS.all))
plot(mu.hat.pls3NS.all, V.link(mu.hat.pls3NS.all)^(-1/3))
plot(mu.hat.pls3NS.all, A.link(mu.hat.pls3NS.all))

ra.hat.pls3NS.all <- (A.link(y.all[,1]) - A.link(mu.hat.pls3NS.all))/V.link(mu.hat.pls3NS.all)^(1/6) # scaled Anscombe residuals

pdf("anova_all_res_ans.pdf",width=10,height=10)
df.ra.pls3NS <- data.frame(tt.all=(1:length(tt)), mu=mu.hat.pls3NS.all, ra=ra.hat.pls3NS.all)
ggplot(data = df.ra.pls3NS, aes(x = tt.all, y = ra)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Anscombe's residuals",sep="")) +
  geom_point(color="cornflowerblue",size=3) + xlab("Observations") + ylab("Ans Res") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.ra.pls3NS, aes(x = ra)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Anscombe's residuals",sep="")) +
  geom_histogram(color="black", fill="cornflowerblue") + xlab("Ans Res") + ylab("Count") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.ra.pls3NS, aes(sample = scale(ra))) + theme(text = element_text(size = 40)) +
  labs(title = paste("Anscombe's residuals",sep="")) +
  stat_qq() + xlab("Ans Res") + ylab("Normal") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))

ggplot(data = df.ra.pls3NS, aes(x = mu, y = ra)) + theme(text = element_text(size = 40)) +
  labs(title = paste("Fitted vs Ans Residuals",sep="")) +
  geom_point(color="cornflowerblue",size=3) + xlab("Fitted") + ylab("Ans Res") +
  theme(plot.title = element_textbox(hjust = 0.5, margin = margin(t = 5, b = 5)))
dev.off()


###########################
## Factorization of yield 
###########################

# Produce factorization of large yield with constraints
coef.pls3 <- read.table(file=paste("anova_best_pls3NS",nc3NS.all,"_coeffs.txt",sep=""))
coef.pls3[order(abs(as.numeric(coef.pls3[,2])),decreasing=TRUE),][1:30,] # top 30 coefficients

IJKL <- order(y.all[,1],decreasing=TRUE)[1:sum(y.all[,1]>0.8)]
y.IJKL <- as.data.frame(y.all[IJKL,1], row.names=rownames(y.all)[IJKL])  # top yields
y.IJKL

cbind(rownames(y.IJKL)[grepl("additive 3", rownames(y.IJKL))], 
  y.IJKL[grepl("additive 3", rownames(y.IJKL)),])

cbind(rownames(y.IJKL)[grepl("additive 3:aryl_halide 2", rownames(y.IJKL))], 
      y.IJKL[grepl("additive 3:aryl_halide 2", rownames(y.IJKL)),])

ijkl <- which(rownames(y.all)=="additive 3:aryl_halide 2:base 0:ligand 0")
y.ijkl <- as.data.frame(cbind(rownames(y.all)[ijkl], y.all[ijkl,]))
y.ijkl

mu.hat.pls3NS.all[ijkl]
xxx.all[ijkl,which(xxx.all[ijkl,]!=0)]
coef.pls3[-1,][which(xxx.all[ijkl,]!=0),]
kappa1(xxx.all[ijkl,]%*%beta.hat.pls3NS.all[-1] + beta.hat.pls3NS.all[1])
kappa1(xxx.all[ijkl,which(xxx.all[ijkl,]!=0)]%*%beta.hat.pls3NS.all[-1][which(xxx.all[ijkl,]!=0)] + beta.hat.pls3NS.all[1])

coef.pls3.ijkl <- rbind(coef.pls3[1,], coef.pls3[-1,][which(xxx.all[ijkl,]!=0),])
coef.pls3.ijkl$V2 <- c(coef.pls3.ijkl$V2[1], as.numeric(xxx.all[ijkl,which(xxx.all[ijkl,]!=0)])*coef.pls3.ijkl$V2[-1])
coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

tags.ijkl <- strsplit(rownames(y.all)[ijkl], split=":")
tags.ijkl

new.ind <- 4:5
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("base 0",new.val))
new.ind <- 4:6
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("ligand 0",new.val))
# coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

new.ind <- 5:6
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("additive 3:base 0",new.val))
new.ind <- 5:7
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("additive 3:ligand 0",new.val))
# coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

new.ind <- 5:6
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("aryl_halide 2:base 0",new.val))
new.ind <- 5:7
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("aryl_halide 2:ligand 0",new.val))
# coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

new.ind <- 5:10
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("base 0:ligand 0",new.val))
# coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

new.ind <- 5:6
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("additive 3:aryl_halide 2:base 0",new.val))
# coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

new.ind <- 5:7
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("additive 3:aryl_halide 2:ligand 0",new.val))
# coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

new.ind <- 5:10
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("additive 3:base 0:ligand 0",new.val))
# coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

new.ind <- 5:10
new.val <- sum(coef.pls3.ijkl[new.ind,2])
coef.pls3.ijkl <- coef.pls3.ijkl[-new.ind,]
coef.pls3.ijkl <- rbind(coef.pls3.ijkl, list("aryl_halide 2:base 0:ligand 0",new.val))
# coef.pls3.ijkl
# kappa1(sum(coef.pls3.ijkl$V2))

# apply(xs, 2, unique)
# apply(xs, 2, function(x) order(unique(x)))
add.true <- paste("additive ", apply(xs, 2, unique)$additive[which(apply(xs, 2, function(x) order(unique(x)))$additive==3)], sep="")
ary.true <- paste("aryl_halide ", apply(xs, 2, unique)$aryl_halide[which(apply(xs, 2, function(x) order(unique(x)))$aryl_halide==2)], sep="")
bas.true <- paste("base ", apply(xs, 2, unique)$base[which(apply(xs, 2, function(x) order(unique(x)))$base==3)], sep="")
lig.true <- paste("ligand ", apply(xs, 2, unique)$ligand[which(apply(xs, 2, function(x) order(unique(x)))$ligand==2)], sep="")

coef.pls3.ijkl$V1 <- c("intercept", add.true, ary.true, paste(add.true, ary.true, sep=":"), bas.true, lig.true,
                       paste(add.true, bas.true, sep=":"), paste(add.true, lig.true, sep=":"), 
                       paste(ary.true, bas.true, sep=":"), paste(ary.true, lig.true, sep=":"),
                       paste(bas.true, lig.true, sep=":"), paste(add.true, ary.true, bas.true, sep=":"),
                       paste(add.true, ary.true, lig.true, sep=":"), paste(add.true, bas.true, lig.true, sep=":"),
                       paste(ary.true, bas.true, lig.true, sep=":") )
coef.pls3.ijkl <- rbind( c("g.link(mu.hat)", eta.hat.pls3NS.all[ijkl]), coef.pls3.ijkl)
coef.pls3.ijkl
write.table(coef.pls3.ijkl, file=paste("anova_best_pls3NS",nc3NS.all,"_yield90_table.txt",sep=""), sep=" ", row.names=FALSE, col.names=FALSE)

# Produce factorization of small yield with constraints
coef.pls3 <- read.table(file=paste("anova_best_pls3NS",nc3NS.all,"_coeffs.txt",sep=""))
coef.pls3[order(abs(as.numeric(coef.pls3[,2])),decreasing=TRUE),][1:30,] # top 30 coefficients

IJKL <- order(y.all[,1],decreasing=TRUE)[-(1:sum(y.all[,1]>0.2))]
y.IJKL <- as.data.frame(y.all[IJKL,1], row.names=rownames(y.all)[IJKL])  # top yields
y.IJKL

cbind(rownames(y.IJKL)[grepl("aryl_halide 15", rownames(y.IJKL))], 
      y.IJKL[grepl("aryl_halide 15", rownames(y.IJKL)),])

cbind(rownames(y.IJKL)[grepl("additive 22:aryl_halide 15", rownames(y.IJKL))], 
      y.IJKL[grepl("additive 22:aryl_halide 15", rownames(y.IJKL)),])

ijkl <- which(rownames(y.all)=="additive 22:aryl_halide 15:base 2:ligand 4")
y.ijkl <- as.data.frame(cbind(rownames(y.all)[ijkl], y.all[ijkl,]))
y.ijkl

mu.hat.pls3NS.all[ijkl]
xxx.all[ijkl,which(xxx.all[ijkl,]!=0)]
coef.pls3[-1,][which(xxx.all[ijkl,]!=0),]
kappa1(xxx.all[ijkl,]%*%beta.hat.pls3NS.all[-1] + beta.hat.pls3NS.all[1])
kappa1(xxx.all[ijkl,which(xxx.all[ijkl,]!=0)]%*%beta.hat.pls3NS.all[-1][which(xxx.all[ijkl,]!=0)] + beta.hat.pls3NS.all[1])

coef.pls3.ijkl <- rbind(coef.pls3[1,], coef.pls3[-1,][which(xxx.all[ijkl,]!=0),])
coef.pls3.ijkl$V2 <- c(coef.pls3.ijkl$V2[1], as.numeric(xxx.all[ijkl,which(xxx.all[ijkl,]!=0)])*coef.pls3.ijkl$V2[-1])
coef.pls3.ijkl

add.true <- paste("additive ", apply(xs, 2, unique)$additive[which(apply(xs, 2, function(x) order(unique(x)))$additive==22)], sep="")
ary.true <- paste("aryl_halide ", apply(xs, 2, unique)$aryl_halide[which(apply(xs, 2, function(x) order(unique(x)))$aryl_halide==15)], sep="")
bas.true <- paste("base ", apply(xs, 2, unique)$base[which(apply(xs, 2, function(x) order(unique(x)))$base==2)], sep="")
lig.true <- paste("ligand ", apply(xs, 2, unique)$ligand[which(apply(xs, 2, function(x) order(unique(x)))$ligand==4)], sep="")

coef.pls3.ijkl$V1 <- c("intercept", add.true, ary.true, bas.true, lig.true, 
                       paste(add.true, ary.true, sep=":"), paste(add.true, bas.true, sep=":"), 
                       paste(add.true, lig.true, sep=":"), paste(ary.true, bas.true, sep=":"), 
                       paste(ary.true, lig.true, sep=":"), paste(bas.true, lig.true, sep=":"), 
                       paste(add.true, ary.true, bas.true, sep=":"),
                       paste(add.true, ary.true, lig.true, sep=":"), 
                       paste(add.true, bas.true, lig.true, sep=":"),
                       paste(ary.true, bas.true, lig.true, sep=":") )
coef.pls3.ijkl <- rbind( c("g.link(mu.hat)", eta.hat.pls3NS.all[ijkl]), coef.pls3.ijkl)
coef.pls3.ijkl   
write.table(coef.pls3.ijkl, file=paste("anova_best_pls3NS",nc3NS.all,"_yield10_table.txt",sep=""), sep=" ", row.names=FALSE, col.names=FALSE)
































